# Site wide configuration

title:            Kristin Gonzalez
locale:           en_US
url:              
baseurl:          /kristin-portfolio

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Kristin Gonzalez
  avatar: bio-photo.jpg
  bio: "Ruby on Rails Developer"
  email: kristingonzalez81@gmail.com
  twitter: kgonzalez81  
  github: kristing81
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: kristingonzalez

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
